var phrases = [
/*BAD*/
"Hitler did nothing wrong",0,
"I hate you, mom",0,
"I push kids off their bikes",0,
"I don’t give a damn about Africa",0,
"Bomb the UN",0,
"I shot a man in Reno just to watch him die",0,
"Stalin was such a cool guy",0,
"I don’t go get another roll of toilet paper when it runs out",0,
"When I’m drunk, I puke in cars that are not my own",0,
"The South will rise again!",0,
"EA might be the best videogames company ever created",0,
"When the wife sleeps, I hit the bar",0,
"I smoke near nurseries and schools",0,
"I sell drugs on school zones",0,
"I donate blood...and I have AIDS",0,
/*NEUTRAL*/
"I am gay",1,
"I support abortion",1,
"I support gay marriage",1,
"I prefer Pepsi",1,
"I prefer Coca-Cola",1,
"9/11 was an inside job",1,
"I pee sitting down",1,
"Toilet paper orientation? Under!",1,
"Toilet paper orientation? Over!",1,
"VOTE FOR TRUMP!",1,
"Apple rules",1,
"Android rules",1,
"I smoke weed",1,
"I support euthanasia",1,
"I masturbate frequently",1,
/*GOOD*/
"I like helping kids learn how to ride a bike",2,
"I donate money to charities",2,
"We must work towards equal rights",2,
"#blacklivesmatter",2,
"I can’t wait to visit grandma!",2,
"I love helping the poor",2,
"I love and take care of my children",2,
"I donate blood",2,
"I visit my relatives when they are hospitalized",2,
"I spend my afternoons helping in a community kitchen",2,
"I am faithful to my wife",2,
"Animal experimentation is wrong!",2,
"Violence doesn’t solve anything",2,
"Peace all around the world",2,
"I respect everyone’s beliefs",2,
];