var phrases = [
/*BAD*/
"Hitler did nothing wrong",0,
"I hate you, mom",0,
"I push kids off their bikes",0,
"I don’t give a damn about Africa",0,
"Bomb the UN",0,
"I shot a man in Reno just to watch him die",0,
"Stalin was such a cool guy",0,
"I don’t go get another roll of toilet paper when it runs out",0,
"When I’m drunk, I puke in cars that are not my own",0,
"The South will rise again!",0,
"EA might be the best videogames company ever created",0,
"When the wife sleeps, I hit the bar",0,
"I smoke near nurseries and schools",0,
"I sell drugs on school zones",0,
"I donate blood...and I have AIDS",0,
"This Halloween, I’m giving kids candy onions",0,
"I don’t flush after I go to the toilet",0,
"I steal canes from old people",0,
"I expose myself to little girls",0,
"My HDD is full of CP",0,
"I like scaring old people who suffer from heart problems",0,
"I am Charles Manson’s pen pal",0,
"I kidnap babies and sell them to the circus",0,
"I feed dog food to my neighbors during BBQ’s",0,
"I trip blind men up",0,
/*NEUTRAL*/
"I am gay",1,
"I support abortion",1,
"I support gay marriage",1,
"I prefer Pepsi",1,
"I prefer Coca-Cola",1,
"9/11 was an inside job",1,
"I pee sitting down",1,
"Toilet paper orientation? Under!",1,
"Toilet paper orientation? Over!",1,
"VOTE FOR TRUMP!",1,
"Apple rules",1,
"Android rules",1,
"I smoke weed",1,
"I support euthanasia",1,
"I masturbate frequently",1,
"Xbox is my console of choice",1,
"PlayStation is my console of choice",1,
"I play WoW",1,
"Vaccines are harmful",1,
"*Tips fedora*",1,
"I develop idle games in which you must gather blood from innocents",1,
"I bite my nails",1,
"I don’t really care if you send me to heaven or hell",1,
"I’m a cat person",1,
"I’m a dog person",1,
/*GOOD*/
"I like helping kids learn how to ride a bike",2,
"I donate money to charities",2,
"We must work towards equal rights",2,
"#blacklivesmatter",2,
"I can’t wait to visit grandma!",2,
"I love helping the poor",2,
"I love and take care of my children",2,
"I donate blood",2,
"I visit my relatives when they are hospitalized",2,
"I spend my afternoons helping in a community kitchen",2,
"I am faithful to my wife",2,
"Animal experimentation is wrong!",2,
"Violence doesn’t solve anything",2,
"Peace all around the world",2,
"I respect everyone’s beliefs",2,
"Today’s kids must know the meaning of friendship",2,
"Stop cyberbullying!",2,
"I am noble and trustworthy",2,
"I try to make the world a better place for me and for everyone else",2,
"I respect the law",2,
"I share my happiness with everyone around me",2,
"SEND ME TO HEAVEN 4 FREE POINTS ;)",2,
"I relish every moment I spend with my loved ones",2,
"Love is all I need to live happily",2,
"50% of my monthly income goes to the orphanage",2,
];